spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zfx666
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true